name: public
named: {}
views:
  uesio/crmsite.getstarted: true
  uesio/crmsite.home: true
  uesio/crmsite.pricing: true
  uesio/crmsite.header: true
  uesio/crmsite.footer: true
collections: {}
routes:
  uesio/crmsite.getstarted: true
  uesio/crmsite.home: true
  uesio/crmsite.pricing: true
files: {}
bots:
  uesio/crmsite.create_site: true
integrationActions:
  uesio/crmsite.studio:
    allowAllActions: true
    actions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: true
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
